from django.shortcuts import render

bohemian_rhapsody = [
    'Is this the real life? Is this just fantasy?',
    'Caught in a landslide, no escape from reality',
    'Open your eyes, look up to the skies and see',
    'I\'m just a poor boy, I need no sympathy',
    'Because I\'m easy come, easy go',
    'Little high, little low',
    'Any way the wind blows doesn\'t really matter to me, to me',
    'Mama, just killed a man',
    'Put a gun against his head, pulled my trigger, now he\'s dead',
    'Mama, life had just begun',
    'But now I\'ve gone and thrown it all away',
    'Mama, ooh, didn\'t mean to make you cry',
    'If I\'m not back again this time tomorrow',
    'Carry on, carry on as if nothing really matters',
    'Too late, my time has come',
    'Sends shivers down my spine, body\'s aching all the time',
    'Goodbye, everybody, I\'ve got to go',
    'Gotta leave you all behind and face the truth',
    'Mama, ooh (any way the wind blows)',
    'I don\'t wanna die',
    'I sometimes wish I\'d never been born at all',
    'I see a little silhouetto of a man',
    'Scaramouche, Scaramouche, will you do the Fandango?',
    'Thunderbolt and lightning, very, very frightening me',
    '(Galileo) Galileo, (Galileo) Galileo, Galileo Figaro, magnifico',
    'But I\'m just a poor boy, nobody loves me',
    'He\'s just a poor boy from a poor family',
    'Spare him his life from this monstrosity',
    'Easy come, easy go, will you let me go?',
    'No, we will not let you go (let him go)',
    'We will not let you go (let him go)',
    'We will not let you go (let me go)',
    'Will not let you go (let me go)',
    'Will not let you go (never, never, never, never let me go)',
    'No, no, no, no, no, no, no',
    'Oh, mamma mia, mamma mia',
    'Mamma mia, let me go',
    'Beelzebub has a devil put aside for me, for me, for me',
    'So you think you can stone me and spit in my eye?',
    'So you think you can love me and leave me to die?',
    'Oh, baby, can\'t do this to me, baby',
    'Just gotta get out, just gotta get right outta here',
    'Ooh',
    'Ooh, yeah, ooh, yeah',
    'Nothing really matters, anyone can see',
    'Nothing really matters',
    'Nothing really matters to me'
]

bohemian_rhapsody_de = [
    'Ist das das wahre Leben? Ist das nur Fantasie?',
    'Gefangen in einer Lawine, kein Entkommen aus der Realität',
    'Öffne deine Augen, schau hinauf in den Himmel und sieh',
    'Ich bin nur ein armer Junge, ich brauche kein Mitleid',
    'Denn ich bin mal so, mal so',
    'Mal hoch, mal tief',
    'Wie der Wind weht, es spielt keine Rolle für mich, für mich',
    'Mama, ich habe gerade einen Mann getötet',
    'Eine Pistole an seinen Kopf gehalten, den Abzug gedrückt, jetzt ist er tot',
    'Mama, das Leben hatte gerade erst begonnen',
    'Aber jetzt habe ich alles weggeworfen',
    'Mama, ooh, wollte dich nicht zum Weinen bringen',
    'Wenn ich morgen nicht zurück bin',
    'Mach weiter, mach weiter, als wäre nichts wirklich wichtig',
    'Zu spät, meine Zeit ist gekommen',
    'Ein Schauer läuft mir über den Rücken, mein Körper schmerzt die ganze Zeit',
    'Lebt wohl, alle zusammen, ich muss gehen',
    'Ich muss euch alle verlassen und der Wahrheit ins Auge sehen',
    'Mama, ooh (wie der Wind weht)',
    'Ich will nicht sterben',
    'Manchmal wünschte ich, ich wäre nie geboren worden',
    'Ich sehe eine kleine Silhouette eines Mannes',
    'Scaramouche, Scaramouche, wirst du den Fandango tanzen?',
    'Donnerschlag und Blitz, sehr, sehr furchterregend für mich',
    '(Galileo) Galileo, (Galileo) Galileo, Galileo Figaro, magnifico',
    'Aber ich bin nur ein armer Junge, niemand liebt mich',
    'Er ist nur ein armer Junge aus einer armen Familie',
    'Verschont sein Leben vor dieser Monstrosität',
    'Mal so, mal so, lässt du mich gehen?',
    'Nein, wir werden dich nicht gehen lassen (lass ihn gehen)',
    'Wir werden dich nicht gehen lassen (lass ihn gehen)',
    'Wir werden dich nicht gehen lassen (lass mich gehen)',
    'Werden dich nicht gehen lassen (lass mich gehen)',
    'Werden dich nicht gehen lassen (niemals, niemals, niemals, niemals lass mich gehen)',
    'Nein, nein, nein, nein, nein, nein, nein',
    'Oh, Mama mia, Mama mia',
    'Mama mia, lass mich gehen',
    'Beelzebub hat einen Teufel für mich beiseitegelegt, für mich, für mich',
    'Also denkst du, du kannst mich steinigen und mir ins Auge spucken?',
    'Also denkst du, du kannst mich lieben und mich sterben lassen?',
    'Oh, Baby, kannst du mir das nicht antun, Baby?',
    'Ich muss einfach raus, ich muss einfach hier raus',
    'Ooh',
    'Ooh, ja, ooh, ja',
    'Nichts spielt wirklich eine Rolle, das kann jeder sehen',
    'Nichts spielt wirklich eine Rolle',
    'Nichts spielt wirklich eine Rolle für mich'
]

bohemian_rhapsody_fr = [
    'Est-ce la vraie vie? Est-ce juste une fantaisie?',
    'Pris dans une avalanche, pas d’échappatoire à la réalité',
    'Ouvre les yeux, regarde le ciel et vois',
    'Je suis juste un pauvre garçon, je n’ai pas besoin de sympathie',
    'Parce que je vais et je viens',
    'Un peu en haut, un peu en bas',
    'Peu importe comment souffle le vent, ça ne compte pas pour moi, pour moi',
    'Maman, je viens de tuer un homme',
    'J’ai mis un pistolet contre sa tête, j’ai appuyé sur la gâchette, maintenant il est mort',
    'Maman, la vie venait juste de commencer',
    'Mais maintenant j’ai tout gâché',
    'Maman, ooh, je ne voulais pas te faire pleurer',
    'Si je ne reviens pas demain',
    'Continue, continue, comme si rien n’avait vraiment d’importance',
    'Trop tard, mon heure est venue',
    'Un frisson me traverse l’échine, mon corps souffre tout le temps',
    'Adieu tout le monde, je dois y aller',
    'Je dois tous vous quitter et affronter la vérité',
    'Maman, ooh (peu importe comment souffle le vent)',
    'Je ne veux pas mourir',
    'Parfois, je souhaiterais ne jamais être né',
    'Je vois une petite silhouette d’un homme',
    'Scaramouche, Scaramouche, feras-tu le Fandango?',
    'Foudre et éclairs, très, très effrayant pour moi',
    '(Galileo) Galileo, (Galileo) Galileo, Galileo Figaro, magnifico',
    'Mais je suis juste un pauvre garçon, personne ne m’aime',
    'Il est juste un pauvre garçon d’une pauvre famille',
    'Épargnez-lui la vie de cette monstruosité',
    'Je vais et je viens, me laisseras-tu partir?',
    'Non, nous ne te laisserons pas partir (laissez-le partir)',
    'Nous ne te laisserons pas partir (laissez-le partir)',
    'Nous ne te laisserons pas partir (laissez-moi partir)',
    'Ne te laisserons pas partir (laissez-moi partir)',
    'Ne te laisserons pas partir (jamais, jamais, jamais, jamais ne me laissez partir)',
    'Non, non, non, non, non, non, non',
    'Oh, mamma mia, mamma mia',
    'Mamma mia, laissez-moi partir',
    'Beelzebub a mis un démon de côté pour moi, pour moi, pour moi',
    'Alors tu penses que tu peux me lapider et me cracher au visage?',
    'Alors tu penses que tu peux m’aimer et me laisser mourir?',
    'Oh, bébé, tu ne peux pas me faire ça, bébé',
    'Je dois juste sortir, je dois juste sortir d’ici',
    'Ooh',
    'Ooh, ouais, ooh, ouais',
    'Rien n’a vraiment d’importance, tout le monde peut voir',
    'Rien n’a vraiment d’importance',
    'Rien n’a vraiment d’importance pour moi'
]


def index(request):
    context = {
        'title': 'Bohemian Rhapsody lyrics',
        'song': bohemian_rhapsody,
    }
    return render(request, 'songs/index.html', context)


def de(request):
    context = {
        'title': 'Bohemian Rhapsody deutsch lyrics',
        'song': bohemian_rhapsody_de,
    }
    return render(request, 'songs/index.html', context)


def fr(request):
    context = {
        'title': 'Bohemian Rhapsody french lyrics',
        'song': bohemian_rhapsody_fr,
    }
    return render(request, 'songs/index.html', context)
